name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/online_shop:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/online_shop:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to AWS EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          # Uncomment the following line if your SSH key has a passphrase
          # passphrase: ${{ secrets.EC2_PASSPHRASE }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/online_shop:latest
            docker stop online_shop || true
            docker rm online_shop || true
            docker run -d -p 3000:3000 --name online_shop ${{ secrets.DOCKERHUB_USERNAME }}/online_shop:latest
